/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#00210c',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#fff2f2',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'inverse-primary': '#7cda93',
        outline: '#6f7a6f',
        'outline-variant': '#becabc',
        'on-tertiary-fixed': '#400012',
        'on-secondary-fixed': '#2e1500',
        'surface-tint': '#006d35',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6b3800',
        background: '#f8f9fa',
        'tertiary-fixed': '#ffd9dd',
        error: '#ba1a1a',
        'surface-dim': '#d9dadb',
        'secondary-container': '#fd9c42',
        'primary-fixed-dim': '#7cda93',
        tertiary: '#95374a',
        'surface-container-lowest': '#ffffff',
        surface: '#f8f9fa',
        'on-surface': '#191c1d',
        'on-secondary-fixed-variant': '#6d3900',
        'tertiary-container': '#b44f61',
        'on-background': '#191c1d',
        secondary: '#904d00',
        'inverse-on-surface': '#f0f1f2',
        'surface-variant': '#e1e3e4',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb2bb',
        'inverse-surface': '#2e3132',
        'surface-container-high': '#e7e8e9',
        'secondary-fixed': '#ffdcc2',
        'on-tertiary': '#ffffff',
        primary: '#006530',
        'primary-fixed': '#97f7ad',
        'primary-container': '#1b8043',
        'surface-container-highest': '#e1e3e4',
        'surface-bright': '#f8f9fa',
        'secondary-fixed-dim': '#ffb77c',
        'on-error-container': '#93000a',
        'on-surface-variant': '#3f493f',
        'on-tertiary-fixed-variant': '#7f2639',
        'on-primary-fixed-variant': '#005226',
        'on-primary-container': '#d6ffd9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '24px',
        'stack-md': '12px',
        'stack-lg': '24px',
        'card-gap': '12px',
        base: '8px',
        'stack-sm': '4px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
