import type { OrderDraft, OrderDraftLine } from '../orderDraft/types';

export type SalesHeaderRequest = { dataAreaId: string; CurrencyCode: string; LanguageId: string; InvoiceCustomerAccountNumber: string; OrderingCustomerAccountNumber: string; OrderResponsiblePersonnelNumber: string; DeliveryAddressLocationId: string; FADlvMode?: string; RequestedShippingDate?: string; ConfirmedShippingDate?: string; MatchingAgreement?: number; CSFASalesAgreementId?: string; CommissionSalesRepresentativeGroupId?: string; TaxExemptNumber?: string; SalesOrderName?: string; SalesOrderOriginCode?: string; Observations?: string; CustomersOrderReference?: string };
export type SalesHeaderResponse = { dataAreaId: string; salesOrderNumber: string; salesOrderName: string; salesOrderStatus: string; customerAccount: string; paymentTermsName: string };
export type SalesLineRequest = { dataAreaId: string; SalesOrderNumber: string; ItemNumber: string; ProductConfigurationId: string; ProductStyleId: string; ProductSizeId: string; ProductColorId: string; ProductVersionId: string; SalesPrice: number; OrderedSalesQuantity: number; ShippingSiteId: string; ShippingWarehouseId: string; CSFASuppItemGroupId?: string; FABonification: '0' | '1' };
export type AgreementLineRequest = SalesLineRequest & { ChangeShippingWarehouseId: string; MatchingAgreementLine: number };
export type ExistingSalesLine = { lineNumber: number; itemNumber: string; productConfigurationId: string; productStyleId: string; productSizeId: string; productColorId: string; productVersionId: string; salesPrice: number; orderedSalesQuantity: number; shippingSiteId: string; shippingWarehouseId: string; csfaSuppItemGroupId: string; faBonification: string };
export type SubmissionStatus = 'idle' | 'validating' | 'creating-header' | 'header-created' | 'creating-lines' | 'recovering' | 'partial-failure' | 'completed' | 'failed';
export type SubmissionLineStatus = 'pending' | 'creating' | 'created' | 'failed';
export type SubmissionLine = { localId: string; status: SubmissionLineStatus; attempts: number; error: string | null; backendLineNumber: number | null; draftLine: OrderDraftLine };
export type OrderSubmission = { schemaVersion: 1; accountId: string; companyId: string; draftId: string; salesOrderNumber: string | null; status: SubmissionStatus; headerAmbiguous: boolean; createdAt: string; updatedAt: string; snapshot: OrderDraft; lines: SubmissionLine[]; error: string | null };
export type SubmissionResult = { submission: OrderSubmission; completed: boolean };
export interface OrderSubmissionGateway { createHeader(request: SalesHeaderRequest): Promise<SalesHeaderResponse>; createNormalLine(request: SalesLineRequest): Promise<ExistingSalesLine[]>; createAgreementLine(request: AgreementLineRequest): Promise<ExistingSalesLine[]>; getExistingLines(companyId: string, salesOrderNumber: string): Promise<ExistingSalesLine[]>; }
