import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => ({ query: vi.fn(), uploader: vi.fn() }));
vi.mock('../../features/attachments/attachmentQueries', () => ({ useOrderAttachments: (id: string) => mocks.query(id), useAttachmentUploader: (id: string) => mocks.uploader(id) }));
import OrderAttachmentsPage from './OrderAttachmentsPage';
afterEach(cleanup);
const mount = () => render(<MemoryRouter initialEntries={['/pedidos/OV-99/adjuntos?customer=C1&page=2']}><Routes><Route path="/pedidos/:salesOrderNumber/adjuntos" element={<OrderAttachmentsPage/>}/><Route path="/pedidos/:salesOrderNumber" element={<p>Detalle conservado</p>}/></Routes></MemoryRouter>);
describe('OrderAttachmentsPage', () => {
  it('loads the direct route and preserves filters on return', () => { mocks.query.mockReturnValue({ isLoading: false, isError: false, data: [] }); mocks.uploader.mockReturnValue({ upload: vi.fn(), refresh: vi.fn() }); mount(); expect(mocks.query).toHaveBeenCalledWith('OV-99'); fireEvent.click(screen.getByText('← Volver al pedido')); expect(screen.getByText('Detalle conservado')).toBeInTheDocument(); });
  it('keeps partial success and retries only the failed file', async () => { const upload = vi.fn().mockResolvedValueOnce({}).mockRejectedValueOnce(new Error('falló')).mockResolvedValueOnce({}); mocks.query.mockReturnValue({ isLoading: false, isError: false, data: [] }); mocks.uploader.mockReturnValue({ upload, refresh: vi.fn() }); mount(); const input = screen.getByLabelText('Seleccionar archivo'); fireEvent.change(input, { target: { files: [new File(['%PDF'], 'A.pdf')] } }); fireEvent.change(input, { target: { files: [new File(['%PDF'], 'B.pdf')] } }); fireEvent.change(screen.getByLabelText('Descripción A.pdf'), { target: { value: 'A' } }); fireEvent.change(screen.getByLabelText('Descripción B.pdf'), { target: { value: 'B' } }); fireEvent.click(screen.getByText('Subir pendientes')); await waitFor(() => expect(screen.getByText('Reintentar')).toBeInTheDocument()); expect(upload).toHaveBeenCalledTimes(2); expect(screen.getByText('Procesado')).toBeInTheDocument(); fireEvent.click(screen.getByText('Reintentar')); await waitFor(() => expect(upload).toHaveBeenCalledTimes(3)); expect(upload.mock.calls.map(call => call[0].name)).toEqual(['A.pdf', 'B.pdf', 'B.pdf']); });
  it('blocks a simultaneous double submit logically', async () => { let release!: () => void; const upload = vi.fn(() => new Promise<void>(resolve => { release = resolve; })); mocks.query.mockReturnValue({ isLoading: false, isError: false, data: [] }); mocks.uploader.mockReturnValue({ upload, refresh: vi.fn() }); mount(); fireEvent.change(screen.getByLabelText('Seleccionar archivo'), { target: { files: [new File(['%PDF'], 'A.pdf')] } }); fireEvent.change(screen.getByLabelText('Descripción A.pdf'), { target: { value: 'A' } }); const button = screen.getByText('Subir pendientes'); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect(upload).toHaveBeenCalledTimes(1)); release(); });
});
