import type { ApiClient } from '../../core/api/apiClient';
import * as map from './mappers';
import type { Agreement, AgreementLine, City, Country, County, Customer, CustomerAddress, DeliveryMode, DocumentTypes, InventoryItem, PageResult, Price, Product, ProductVariant, PromotionGroup, SalesOrigin, State, VatNumber, ZipCode } from './types';
type Json = Record<string, unknown>; type Signal = { signal?: AbortSignal }; const paging = (page: number, perpage: number) => ({ page, perpage });
const inventoryList = (value: unknown) => Array.isArray(value) ? value as Json[] : value && typeof value === 'object' ? [value as Json] : [];

export const catalogService = (api: ApiClient) => ({
  async customers(input: { company: string; salesGroup: string; search: string; page: number; perPage: number } & Signal): Promise<PageResult<Customer>> { const r = await api.post<Json>('/customer/data', { company: input.company, sales_group: input.salesGroup, search_text: input.search, pagination: paging(input.page, input.perPage) }, input); if (Array.isArray(r)) return map.pageResult([], {}, input.perPage); return map.pageResult(map.list(r.customers).map(map.customer), r.pagination, input.perPage); },
  async customerAddresses(company: string, account: string, options?: Signal): Promise<CustomerAddress[]> { return (await api.post<Json[]>('/customer/address', { company, account_id: account }, options)).map(map.customerAddress); },
  async products(input: { company: string; search: string; page: number; perPage: number; forceRegistry?: boolean } & Signal): Promise<PageResult<Product>> { const r = await api.post<Json>('/company/products', { company: input.company, search_text: input.search, pagination: paging(input.page, input.perPage), force_registry: input.forceRegistry ? 'true' : 'false' }, input); return map.pageResult(map.list(r.products).map(map.product), r.pagination, input.perPage); },
  async variants(input: { company: string; itemId: string; page?: number; perPage?: number; forceRegistry?: boolean; regionId?: string } & Signal): Promise<PageResult<ProductVariant>> { const page = input.page ?? 1, perPage = input.perPage ?? 100; const body: Json = { company: input.company, itemid: input.itemId, pagination: paging(page, perPage), force_registry: input.forceRegistry ? 'true' : 'false' }; if (input.forceRegistry && input.regionId) body.regionid = input.regionId; const r = await api.post<Json>('/company/products/variants', body, input); return map.pageResult(map.list(r.variants).map(map.variant), r.pagination, perPage); },
  async inventory(input: { company: string; salesGroup: string; itemId?: string; search?: string; page?: number; perPage?: number; byWarehouse?: boolean } & Signal): Promise<PageResult<InventoryItem>> { const page = input.page ?? 1, perPage = input.perPage ?? 10; const r = await api.post<Json>('/inventory', { company: input.company, ...(input.itemId ? { itemid: input.itemId } : {}), multi_company: false, by_warehouse: input.byWarehouse ?? true, ...(input.search ? { search_text: input.search } : {}), sales_group: input.salesGroup, pagination: paging(page, perPage) }, input); return map.pageResult(inventoryList(r.inventory).map(map.inventory), r.pagination, perPage); },
  async variantInventory(input: { company: string; salesGroup: string; itemId: string; displayProductNumber: string; page?: number; perPage?: number } & Signal): Promise<PageResult<InventoryItem>> { const page = input.page ?? 1, perPage = input.perPage ?? 10; const r = await api.post<Json>('/inventory/variant', { company: input.company, itemid: input.itemId, variantproduct: input.displayProductNumber, multi_company: false, by_warehouse: true, sales_group: input.salesGroup, pagination: paging(page, perPage) }, input); return map.pageResult(inventoryList(r.inventory).map(map.inventory), r.pagination, perPage); },
  async getPrice(input: { company: string; currency: string; itemId: string; customerAccount: string; configId?: string; colorId?: string; sizeId?: string; styleId?: string; versionId?: string } & Signal): Promise<Price> { return map.price(await api.post<Json>('/d365_services/get_price', { Company: input.company, Currencycode: input.currency, ItemId: input.itemId, CustAccount: input.customerAccount, ConfigId: input.configId ?? '', InventColorId: input.colorId ?? '', InventSizeId: input.sizeId ?? '', InventStyleId: input.styleId ?? '', InventVersionId: input.versionId ?? '' }, input)); },
  async deliveryModes(company: string, options?: Signal): Promise<DeliveryMode[]> { const r = await api.post<Json>('/delivery/mode', { company, pagination: paging(1, 100) }, options); return Array.isArray(r) ? [] : map.list(r.mode).map(map.deliveryMode); },
  async salesOrigins(company: string, options?: Signal): Promise<SalesOrigin[]> { return (await api.post<Json[]>('/company/sales_origin', { company }, options)).map(map.salesOrigin); },
  async agreements(company: string, account: string, options?: Signal): Promise<PageResult<Agreement>> { const r = await api.post<Json>('/customer/agreement', { company, account_id: account, pagination: paging(1, 100) }, options); return map.pageResult(map.list(r.agreement).map(map.agreement), r.pagination, 100); },
  async agreementDetails(recid: number, options?: Signal): Promise<Json> { return api.post<Json>('/customer/agreement/details', { recid, pagination: paging(1, 100) }, options); },
  async partialAgreementLines(company: string, account: string, recid: number, options?: Signal): Promise<AgreementLine[]> { const r = await api.post<unknown>('/customer/agreement/parcial_lines', { company, account_id: account, recid }, options); const j = Array.isArray(r) ? { parcial_lines: r } : r as Json; const raw = j.parcial_lines ?? j.parcialLines ?? j.lines; return map.list(raw).map(map.agreementLine); },
  async promotions(company: string, options?: Signal): Promise<PromotionGroup[]> { const r = await api.post<Json>('/suppItemGroup', { company, pagination: paging(1, 100) }, options); return map.list(r.suppitemgroup).map(map.promotion); },
  async countries(search = '', options?: Signal): Promise<Country[]> { const r = await api.get<Json>('/d365/address/country_regions', { body: { filters: {}, ...(search ? { search_text: search } : {}), page: 1, perpage: 100 }, ...options }); return map.list(r['@odata']).map(map.country); },
  async states(countryId: string, options?: Signal): Promise<State[]> { const r = await api.get<Json>('/d365/address/states', { body: { filters: { CountryRegionId: [countryId] }, page: 1, perpage: 100 }, ...options }); return map.list(r['@odata']).map(map.state); },
  async counties(countryId: string, stateId: string, options?: Signal): Promise<County[]> { const r = await api.get<Json>('/d365/address/counties', { body: { filters: { CountryRegionId: [countryId], StateId: [stateId] }, page: 1, perpage: 100 }, ...options }); return map.list(r['@odata']).map(map.county); },
  async cities(countryId: string, stateId: string, countyId: string, options?: Signal): Promise<City[]> { const r = await api.get<Json>('/d365/address/cities', { body: { filters: { CountryRegionId: [countryId], StateId: [stateId], CountyId: [countyId] }, page: 1, perpage: 100 }, ...options }); return map.list(r['@odata']).map(map.city); },
  async zipCodes(countryId: string, stateId: string, countyId: string, cityId: string, options?: Signal): Promise<ZipCode[]> { const r = await api.get<Json>('/d365/address/zip_codes', { body: { filters: { CountryRegionId: [countryId], State: [stateId], County: [countyId], City: [cityId] } }, ...options }); return map.list(r['@odata']).map(map.zip); },
  async vatNumbers(company: string, countryId: string, name = '', options?: Signal): Promise<PageResult<VatNumber>> { const r = await api.get<Json>('/d365/vat_num', { body: { filters: { Name: name, dataAreaId: company, CountryRegionId: countryId }, sort: { fields: [{ name: 'VATNum', order: 'asc' }] }, page: 1, perpage: 25 }, ...options }); return map.pageResult(map.list(r['@odata']).map(map.vat), r.pagination, 25); },
  async documentTypes(company: string, countryId: string, options?: Signal): Promise<DocumentTypes> { return map.documentTypes(await api.get<Json>('/d365/vat_num/document_type', { body: { filters: { dataAreaId: company, CountryRegionId: countryId } }, ...options })); },
});
